// Steal everything
steal.plugins(
	"jqueryui/accordion",
	"jqueryui/autocomplete",
	"jqueryui/button",
	"jqueryui/datepicker",
	"jqueryui/dialog",
	"jqueryui/draggable",
	"jqueryui/droppable",
	"jqueryui/effects",
	"jqueryui/mouse",
	"jqueryui/position",
	"jqueryui/progressbar",
	"jqueryui/resizable",
	"jqueryui/selectable",
	"jqueryui/slider",
	"jqueryui/sortable",
	"jqueryui/tabs"
);
